--ALUMNO
CREATE SEQUENCE ALUMNO_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE JJBT_ALUMNO (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    DIRECCION VARCHAR2(200),
    EDAD NUMBER
);

--PROFESOR
CREATE SEQUENCE PROFESOR_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE JJBT_PROFESOR (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL
);

--CALIFICACION
CREATE SEQUENCE CALIFICACION_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE JJBT_CALIFICACION (
    ID NUMBER PRIMARY KEY,
    MATERIA VARCHAR2(100) NOT NULL,
    NOTA1 NUMBER(4,2) NOT NULL,
    NOTA2 NUMBER(4,2) NOT NULL,
    NOTA3 NUMBER(4,2) NOT NULL,
    ALUMNO_ID NUMBER NOT NULL,
    PROFESOR_ID NUMBER NOT NULL,
    CONSTRAINT FK_CALIF_ALUMNO
        FOREIGN KEY (ALUMNO_ID)
        REFERENCES ALUMNO(ID),
    CONSTRAINT FK_CALIF_PROFESOR
        FOREIGN KEY (PROFESOR_ID)
        REFERENCES PROFESOR(ID)
);


